### PR TITLE
Zero out the score

### PR DESCRIPTION
**Pull request by dramalho**
BECAUSE DAVID WANTS TO!

### CODE REVIEW

**Comment by Intrepidd** [comment]
sup guys, this repo is public, careful with the links and the sensitive message content ;)

**Comment by dramalho** [comment]
GOD DAMN IT

**Comment by zeto** [comment]
👍

**Comment by dramalho** [comment]
:') AMIGO

**Comment by conorhynesire** [comment]
nerd

**Comment by conorhynesire** [comment]
👍

**Comment by dramalho** [comment]
what's a famous youtuber person doing in these parts? :D

**Pull request merged**
